# Task 3 - Python + SQL Integration

## Objective
Integrate python with MySQL using SQLAlchemy and Pymysql,
execute SQL queries froM Jupyter notebook, and load results
into pandas dataframes.

In [7]:
import sys
sys.path.insert(0, "..")

import pandas as pd
from sqlalchemy import create_engine
from db_utils import get_engine

print("Pandas:", pd.__version__)
print("SQLAlchemy imported successfully")
print("db_utils imported successfully")

Pandas: 2.3.3
SQLAlchemy imported successfully
db_utils imported successfully

In [8]:
engine = get_engine()

print("SQLAlchemy engine created successfully!")

SQLAlchemy engine created successfully!

In [9]:
with engine.connect() as connection:
    print("MySQL database connected successfully!")

MySQL database connected successfully!

In [10]:
query = """
SELECT
    Customer_ID,
    total_revenue
FROM telco_clean
ORDER BY total_revenue DESC
LIMIT 10;
"""

In [12]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text(query))

    for row in result:
        print(row)

('0164-APGRB', 11979.34)
('8263-QMNTJ', 11868.34)
('5451-YHYPW', 11795.78)
('3810-DVDQQ', 11688.9)
('7569-NMZYQ', 11634.53)
('3963-RYFNS', 11596.99)
('9351-HXDMR', 11564.37)
('5914-XRFQB', 11529.54)
('0619-OLYUR', 11514.81)
('3508-CFVZL', 11501.82)

In [13]:
df = pd.read_sql(query, engine)

In [14]:
df

  Customer_ID  total_revenue
0  0164-APGRB       11979.34
1  8263-QMNTJ       11868.34
2  5451-YHYPW       11795.78
3  3810-DVDQQ       11688.90
4  7569-NMZYQ       11634.53
5  3963-RYFNS       11596.99
6  9351-HXDMR       11564.37
7  5914-XRFQB       11529.54
8  0619-OLYUR       11514.81
9  3508-CFVZL       11501.82

In [15]:
print("Rows:", len(df))
print("Columns:", df.columns.tolist())

Rows: 10
Columns: ['Customer_ID', 'total_revenue']

In [16]:
min_revenue = 5000

In [17]:
query + """
SELECT
Customer_ID,
total_revenue
FROM telco_clean
WHERE total_revenue > :min_revenue
ORDER BY total_revenue DESC;
"""

'\nSELECT\n    Customer_ID,\n    total_revenue\nFROM telco_clean\nORDER BY total_revenue DESC\nLIMIT 10;\n\nSELECT\nCustomer_ID,\ntotal_revenue\nFROM telco_clean\nWHERE total_revenue > :min_revenue\nORDER BY total_revenue DESC;\n'

In [18]:
df = pd.read_sql(
    query,
    engine,
    params={"min_revenue": min_revenue}
)
df.head(10)

  Customer_ID  total_revenue
0  0164-APGRB       11979.34
1  8263-QMNTJ       11868.34
2  5451-YHYPW       11795.78
3  3810-DVDQQ       11688.90
4  7569-NMZYQ       11634.53
5  3963-RYFNS       11596.99
6  9351-HXDMR       11564.37
7  5914-XRFQB       11529.54
8  0619-OLYUR       11514.81
9  3508-CFVZL       11501.82

# Task 3 Summary

## Work Completed

- Connected Python to MySQL using SQLAlchemy and PyMySQL.
- Executed SQL queries directly from Jupyter Notebook.
- Used `pandas.read_sql()` to load SQL query results into Pandas DataFrames.
- Implemented parameterized SQL queries.
- Created a reusable `db_utils.py` module for database connections.

## Tools Used

- Python
- MySQL
- SQLAlchemy
- PyMySQL
- Pandas
- Jupyter Notebook